[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
serviceName = "stockholm-bus-app"

[services.variables]
ENVIRONMENT = "production"
CORS_ORIGINS = "https://${{RAILWAY_PUBLIC_DOMAIN}}"
